clone_folder: "c:\\WORK"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
  matrix:
    - GHCVER: "8.2.2"
    - GHCVER: "8.0.2"

#cache:
# - "C:\\SR"

install:
 - "choco install -y ghc --version %GHCVER%"
 - "choco install -y msys2"
 - "set PATH=C:\\tools\\msys64\\usr\\bin;%PATH%"
 - "refreshenv"
 - "cabal --version"
 - "ghc   --version"
 - "cabal %CABOPTS% update -v"

build: off

test_script:
 - "autoreconf -i"
 - "echo packages:. > cabal.project"
 - "cabal %CABOPTS% new-build -j1 all"
